// PatronDialogues_Instigator.cs
using NightAtTheBar.Dialogue;

namespace NightAtTheBar
{
    public static class PatronDialogues_Instigator
    {
        public static PatronDialogue Build() => PatronDialogueFactory.Create(
            id:                  PatronId.Instigator,
            startingFriendship:  0,
            drunkRejection:      null,
            coolGreeting:        "Not feeling it tonight.",
            hostileGreeting:     "You got something to say?",
            antagonistGreeting:  "You got something to say? Because it looks like you got something to say.",
            fightLine:           "They grab your collar. Bar goes quiet.",
            deEscalateLine:      "\"Easy.\" You say it before they can swing.",
            postFightLine:       "Want a rematch? Clean this time.",

            // ── Arc 1: Arm wrestle ───────────────────────────────────────────
            ArcBuilder.Create(PatronId.Instigator, "ins_arc1", "You. Me. Right now.", 1, FriendshipTier.Stranger)
                .Beat("i1_b1", "You look like you can handle yourself.")
                    .Choice("i1_b1_a", "Depends on the situation.")
                        .Friendship(12)
                        .Log("\"Arm wrestle. The situation is arm wrestle.\"")
                        .GoTo("i1_b2")
                    .Choice("i1_b1_b", "Not really.", "Not... really.")
                        .Friendship(15)
                        .Log("\"Liar.\" They're already grinning.")
                        .GoTo("i1_b2")
                    .Choice("i1_b1_c", "I can.")
                        .Friendship(10)
                        .TriggerEvent("arm_wrestle_immediate")
                        .End()
                .Beat("i1_b2", "Come on. Five seconds. Winner buys.")
                    .Choice("i1_b2_a", "Fine.")
                        .Friendship(10)
                        .TriggerEvent("arm_wrestle")
                        .End()
                    .Choice("i1_b2_b", "Buy me a drink first.")
                        .Friendship(15)
                        .Drunk(15)
                        .Log("\"Ha! Deal.\" They do. Then the arm wrestle.")
                        .TriggerEvent("arm_wrestle")
                        .End()
                    .Choice("i1_b2_c", "I'm saving my strength.")
                        .Friendship(12)
                        .Log("\"For what?\" The question hangs there.")
                        .End()
                .Build(),

            // ── Arc 2: Accountant reveal ─────────────────────────────────────
            ArcBuilder.Create(PatronId.Instigator, "ins_arc2", "What do you actually do?", 2, FriendshipTier.Acquaintance)
                .RequiresArc("ins_arc1")
                .Beat("i2_b1", "You want to know something funny?")
                    .Choice("i2_b1_a", "Always.")
                        .Friendship(15)
                        .Log("\"I'm an accountant.\" Dead serious.")
                        .GoTo("i2_b2")
                    .Choice("i2_b1_b", "Sure.")
                        .Friendship(15)
                        .Log("\"I do taxes.\" Same delivery.")
                        .GoTo("i2_b2")
                    .Choice("i2_b1_c", "Hit me.", "Hit... me.")
                        .Friendship(12)
                        .Log("\"CPA. Twelve years.\"")
                        .GoTo("i2_b2")
                .Beat("i2_b2", "Go ahead. Say it.")
                    .Choice("i2_b2_a", "I wasn't going to say anything.")
                        .Friendship(15)
                        .Log("\"Everyone says something.\"")
                        .GoTo("i2_b3")
                    .Choice("i2_b2_b", "It tracks actually.")
                        .Friendship(18)
                        .Log("They blink. \"How?\"")
                        .GoTo("i2_b3")
                    .Choice("i2_b2_c", "Do you love it?")
                        .Friendship(20)
                        .Log("Long pause. \"I'm very good at it.\" That's not an answer.")
                        .GoTo("i2_b3")
                    .Choice("i2_b2_d", "*laugh dismissively*")
                        .Friendship(-20)
                        .Log("Something shifts in their expression.")
                        .GoTo("i2_b3_hostile")
                .Beat("i2_b3", "The bar thing is separate. This is separate. You understand.")
                    .Choice("i2_b3_a", "Two different people.")
                        .Friendship(18)
                        .Log("\"One person. Two rooms.\"")
                    .Choice("i2_b3_b", "Makes sense.")
                        .Friendship(15)
                    .Choice("i2_b3_c", "Which one's real?")
                        .Friendship(20)
                        .Log("\"Both. Neither. Pick one.\"")
                .Beat("i2_b3_hostile", "You think that's funny? The accounting thing?")
                    .Choice("i2_bh_a", "I wasn't laughing at you.")
                        .Friendship(-20)
                        .Log("\"Looked like it.\" Arm wrestle offered as reset.")
                        .TriggerEvent("arm_wrestle_reset")
                        .End()
                    .Choice("i2_bh_b", "A little bit.")
                        .Friendship(-50)
                        .Log("\"Right.\"")
                        .End()
                    .Choice("i2_bh_c", "*apologise genuinely*")
                        .Friendship(-25)
                        .Log("\"Whatever.\" Cold but not escalating.")
                        .End()
                .Build(),

            // ── Arc 3: The knee ──────────────────────────────────────────────
            ArcBuilder.Create(PatronId.Instigator, "ins_arc3", "The knee", 3, FriendshipTier.Acquaintance)
                .RequiresArc("ins_arc2")
                .Beat("i3_b1", "I played football. Semi-pro. Did I mention that?")
                    .Choice("i3_b1_a", "You didn't.")
                        .Friendship(12)
                        .Log("\"Linebacker. Four seasons.\"")
                        .GoTo("i3_b2")
                    .Choice("i3_b1_b", "No, what happened?")
                        .Friendship(18)
                        .Log("\"How'd you know something happened?\"")
                        .GoTo("i3_b2")
                    .Choice("i3_b1_c", "What position?")
                        .Friendship(15)
                        .Log("\"Linebacker.\" They say it the way people say words that used to mean more.")
                        .GoTo("i3_b2")
                .Beat("i3_b2", "Blew my knee out at twenty-four. Preseason. Didn't even make the papers.")
                    .Choice("i3_b2_a", "I'm sorry.")
                        .Friendship(15)
                        .Log("\"Don't be. It was a long time ago.\" Said in the way that means it wasn't.")
                        .GoTo("i3_b3")
                    .Choice("i3_b2_b", "What did you do after?")
                        .Friendship(20)
                        .Log("\"Finished my degree. Got certified. Been doing taxes ever since.\"")
                        .GoTo("i3_b3")
                    .Choice("i3_b2_c", "Do you miss it?")
                        .Friendship(25)
                        .Log("Long pause. Longer than anything else in their arc. \"Every single day.\"")
                        .GoTo("i3_b3")
                .Beat("i3_b3", "The bar thing is...")
                    .Choice("i3_b3_a", "A way to feel it again?")
                        .Friendship(20)
                        .Log("\"Something like that.\"")
                    .Choice("i3_b3_b", "You're still competitive.")
                        .Friendship(15)
                        .Log("\"I'm always competitive. That didn't go anywhere.\"")
                    .Choice("i3_b3_c", "*say nothing*")
                        .Friendship(18)
                        .Log("\"Appreciate you not making it a thing.\"")
                .Build(),

            // ── Arc 4: Somewhere ─────────────────────────────────────────────
            ArcBuilder.Create(PatronId.Instigator, "ins_arc4", "Somewhere", 4, FriendshipTier.Friend)
                .RequiresArc("ins_arc3")
                .Beat("i4_b1", "Hey.", "*quieter tonight*")
                    .Choice("i4_b1_a", "Hey.")
                        .Friendship(12)
                        .GoTo("i4_b2")
                    .Choice("i4_b1_b", "No arm wrestling tonight?")
                        .Friendship(15)
                        .Log("\"Nah.\"")
                        .GoTo("i4_b2")
                    .Choice("i4_b1_c", "You alright?")
                        .Friendship(12)
                        .Log("\"Yeah. Just thinking.\"")
                        .GoTo("i4_b2")
                .Beat("i4_b2", "You ever miss feeling like you were going somewhere?")
                    .Choice("i4_b2_a", "Yeah.")
                        .Friendship(20)
                        .Log("\"What was it for you?\"")
                        .GoTo("i4_b3")
                    .Choice("i4_b2_b", "Sometimes.")
                        .Friendship(15)
                        .Log("\"I miss it all the time.\"")
                        .GoTo("i4_b3")
                    .Choice("i4_b2_c", "Where were you going?")
                        .Friendship(18)
                        .Log("\"Didn't matter. That was the point. Just... forward.\"")
                        .GoTo("i4_b3")
                .Beat("i4_b3", "This is embarrassing. Forget I said anything.")
                    .Choice("i4_b3_a", "Nothing to forget.")
                        .Friendship(20)
                        .Log("\"Yeah. Okay.\"")
                    .Choice("i4_b3_b", "It's not embarrassing.")
                        .Friendship(15)
                        .Log("\"Little bit.\" But they're okay with it.")
                    .Choice("i4_b3_c", "*say nothing*")
                        .Friendship(20)
                        .Log("They nod once. Thanks you without saying so.")
                .Build(),

            // ── Arc 5: Saved you a seat ──────────────────────────────────────
            ArcBuilder.Create(PatronId.Instigator, "ins_arc5", "Saved you a seat", 5, FriendshipTier.Friend)
                .RequiresArc("ins_arc4")
                .RequiresNight(1)
                .Beat("i5_b1",
                    "They're at the bar, not the booth. A stool next to them is clearly being saved. They slide a drink over without looking.")
                    .Choice("i5_b1_a", "Who's playing?")
                        .Friendship(15)
                        .Log("They tell you. Good game or bad game, they watch it the same way.")
                        .GoTo("i5_b2")
                    .Choice("i5_b1_b", "Good game?")
                        .Friendship(12)
                        .Log("\"Getting there.\"")
                        .GoTo("i5_b2")
                    .Choice("i5_b1_c", "*just watch with them*")
                        .Friendship(20)
                        .GoTo("i5_b2")
                .Beat("i5_b2", "Same time next week?")
                    .Choice("i5_b2_a", "Same time next week.")
                        .Friendship(15)
                        .Log("Something settled between you.")
                    .Choice("i5_b2_b", "*say nothing, just nod*")
                        .Friendship(15)
                    .Choice("i5_b2_c", "You buying?")
                        .Friendship(25)
                        .Style(10)
                        .Log("They laugh. Loud. Like before but lighter. \"Yeah. Yeah I'm buying.\"")
                .Build(),

            // ── Negative arcs ────────────────────────────────────────────────
            ArcBuilder.Create(PatronId.Instigator, "ins_neg_hostile", "You think that's funny?", 10, FriendshipTier.Hostile, FriendshipTier.Hostile)
                .Negative().Repeatable()
                .Beat("inh_b1", "You think that's funny? The accounting thing?")
                    .Choice("inh_b1_a", "I wasn't laughing at you.")
                        .Friendship(-20)
                        .Log("\"Looked like it.\" Cold. Arm wrestle offered as reset — win it and jump back to 0.")
                        .TriggerEvent("arm_wrestle_reset")
                        .End()
                    .Choice("inh_b1_b", "A little bit.")
                        .Friendship(-50)
                        .Log("\"Right.\"")
                        .End()
                    .Choice("inh_b1_c", "*apologise genuinely*")
                        .Friendship(-25)
                        .Log("\"Whatever.\" Cold but not escalating.")
                        .End()
                .Build(),

            ArcBuilder.Create(PatronId.Instigator, "ins_neg_antagonist", "Got something to say?", 11, FriendshipTier.Antagonist, FriendshipTier.Antagonist)
                .Negative().Repeatable()
                .Beat("ina_b1", "They've been watching you for a while. \"You got something to say?\"")
                    .Choice("ina_b1_a", "No.")
                        .Friendship(0)
                        .Log("\"Good.\" Stays hostile but no fight.")
                        .End()
                    .Choice("ina_b1_b", "Yeah actually.", "Yeah... actually.")
                        .ShowIfDrunkAbove(70)
                        .Friendship(-15)
                        .TriggerFight()
                        .End()
                    .Choice("ina_b1_b2", "Yeah actually.")
                        .ShowIfDrunkBelow(70)
                        .Friendship(-10)
                        .Log("You say something. It doesn't land well. But no swing.")
                        .End()
                    .Choice("ina_b1_c", "*say nothing*")
                        .Friendship(-15)
                        .Log("They come closer.")
                        .End()
                .Build(),

            // ── Fight arc ────────────────────────────────────────────────────
            ArcBuilder.Create(PatronId.Instigator, "ins_fight", "The Fight", 12, FriendshipTier.Fight, FriendshipTier.Fight)
                .Fight()
                .Beat("if_b1", "They grab your collar. Bar goes quiet.")
                    .Choice("if_b1_a", "\"Easy.\"")
                        .ShowIfDrunkBelow(50)
                        .Friendship(60)
                        .Style(15)
                        .Log("They let go. Respect. Back to -40.")
                        .End()
                    .Choice("if_b1_a2", "\"Easy.\"")
                        .ShowIfDrunkAbove(50)
                        .Friendship(-10)
                        .Log("Too drunk to sell it. They don't believe you.")
                        .TriggerFight()
                        .End()
                    .Choice("if_b1_b", "*swing first*")
                        .Friendship(-20)
                        .TriggerFight()
                        .TriggerEvent("bar_fight_mutual")
                        .End()
                .Build(),

            // ── Recovery arc (next night after fight) ────────────────────────
            ArcBuilder.Create(PatronId.Instigator, "ins_recovery", "Rematch", 13, FriendshipTier.Cool, FriendshipTier.Hostile)
                .Recovery().RequiresNight(1)
                .Beat("ir_b1", "Want a rematch? Clean this time.")
                    .Choice("ir_b1_a", "Let's go.")
                        .Friendship(30)
                        .TriggerEvent("arm_wrestle_reset")
                        .Log("Win: +10 to 0. Lose: -40.")
                    .Choice("ir_b1_b", "Not yet.")
                        .Friendship(10)
                        .Log("They shrug. The offer stands.")
                .Build()
        );
    }
}
