// PatronDialogues_Regular.cs
using NightAtTheBar.Dialogue;

namespace NightAtTheBar
{
    public static class PatronDialogues_Regular
    {
        public static PatronDialogue Build() => PatronDialogueFactory.Create(
            id:                  PatronId.Regular,
            startingFriendship:  5,
            drunkRejection:      null, // Regular doesn't reject drunk players
            coolGreeting:        "Evening.",
            hostileGreeting:     "Not tonight.",
            antagonistGreeting:  "I've been sitting in this bar for years. I know when someone doesn't respect it.",
            fightLine:           null, // Regular doesn't fight — calls bartender instead
            deEscalateLine:      null,
            postFightLine:       "You going to behave yourself tonight?",

            // ── Positive arcs ───────────────────────────────────────────────
            ArcBuilder.Create(PatronId.Regular, "reg_arc1", "You come here a lot?", 1, FriendshipTier.Stranger)
                .Repeatable()
                .Beat("r1_b1", "You look like you've been here before.")
                    .Choice("r1_b1_a", "First time actually.")
                        .Friendship(10)
                        .Log("\"Could've fooled me. You've got the posture of a regular.\"")
                        .GoTo("r1_b2")
                    .Choice("r1_b1_b", "Too much probably.", "Too mush probably.")
                        .Friendship(15)
                        .Log("He nods slowly. \"Yeah. Me too.\" A pause that doesn't need filling.")
                        .GoTo("r1_b2")
                    .Choice("r1_b1_c", "...")
                        .Friendship(8)
                        .Log("He raises his glass. Doesn't push it.")
                        .GoTo("r1_b2")
                .Beat("r1_b2", "Good bar though. As bars go.")
                    .Choice("r1_b2_a", "What makes a bar good?")
                        .Friendship(12)
                        .UnlockArc("reg_arc2")
                        .Log("\"Consistency. You always know what you're getting.\"")
                        .GoTo("r1_b3")
                    .Choice("r1_b2_b", "I've seen worse.")
                        .Friendship(10)
                        .Log("\"Most of 'em are worse. That's the trick.\"")
                        .GoTo("r1_b3")
                    .Choice("r1_b2_c", "It's alright.")
                        .Friendship(8)
                        .Log("He nods. \"Yeah.\"")
                        .GoTo("r1_b3")
                .Beat("r1_b3", "Well. Drink up.")
                    .Choice("r1_b3_a", "Same to you.")
                        .Friendship(10)
                    .Choice("r1_b3_b", "*raise glass*")
                        .Friendship(10)
                        .Log("No words needed.")
                    .Choice("r1_b3_c", "I'll see you around.")
                        .Friendship(8)
                        .Log("He watches you go.")
                .Build(),

            ArcBuilder.Create(PatronId.Regular, "reg_arc2", "Used to be mine", 2, FriendshipTier.Acquaintance)
                .RequiresArc("reg_arc1")
                .Beat("r2_b1", "You know they changed the barstools since I was last behind that bar.")
                    .Choice("r2_b1_a", "Wait — you worked here?")
                        .Friendship(15)
                        .Log("\"Owned it. Long time ago.\" He says it like it costs something.")
                        .GoTo("r2_b2")
                    .Choice("r2_b1_b", "Behind the bar?")
                        .Friendship(15)
                        .Log("\"Other side of it. Owned the place.\"")
                        .GoTo("r2_b2")
                    .Choice("r2_b1_c", "...")
                        .Friendship(5)
                        .Log("He lets it sit. Doesn't elaborate unless asked.")
                        .GoTo("r2_b3")
                .Beat("r2_b2", "Twelve years. Built it up from a sports bar. Terrible idea, sports bar. Too much yelling.")
                    .Choice("r2_b2_a", "Why'd you sell?")
                        .Friendship(10)
                        .UnlockArc("reg_arc3")
                        .Log("He looks at his drink. \"Had to.\" Pause. \"You want another?\"")
                        .GoTo("r2_b3")
                    .Choice("r2_b2_b", "Do you miss it?")
                        .Friendship(12)
                        .Log("\"Every day. But you can't own something like this and be a customer too.\"")
                        .GoTo("r2_b3")
                    .Choice("r2_b2_c", "Twelve years is a long time.")
                        .Friendship(8)
                        .Log("\"It was.\"")
                        .GoTo("r2_b3")
                .Beat("r2_b3", "New owners aren't bad. Keep the lights low. That's all I ever asked.")
                    .Choice("r2_b3_a", "They do a good job.")
                        .Friendship(10)
                        .Log("He nods. \"Close enough.\"")
                    .Choice("r2_b3_b", "Would you ever buy it back?")
                        .Friendship(12)
                        .Log("Long pause. \"No.\" No explanation.")
                    .Choice("r2_b3_c", "*say nothing*")
                        .Friendship(8)
                        .Log("He finishes his drink. \"Right then.\"")
                .Build(),

            ArcBuilder.Create(PatronId.Regular, "reg_arc3", "Had to", 3, FriendshipTier.Acquaintance)
                .RequiresArc("reg_arc2")
                .Beat("r3_b1", "You asked why I sold.", "You asked why I... sold.")
                    .Choice("r3_b1_a", "You don't have to tell me.")
                        .Friendship(15)
                        .Log("\"I know.\" He tells you anyway.")
                        .GoTo("r3_b2")
                    .Choice("r3_b1_b", "Yeah.")
                        .Friendship(15)
                        .Log("He takes a sip first. Then: \"My wife got sick.\"")
                        .GoTo("r3_b2")
                    .Choice("r3_b1_c", "*say nothing*")
                        .Friendship(12)
                        .Log("He needed to say it to someone.")
                        .GoTo("r3_b2")
                .Beat("r3_b2", "Treatment wasn't cheap. Bar was the only thing worth enough.")
                    .Choice("r3_b2_a", "Did it work?")
                        .Friendship(15)
                        .Log("The longest pause of any conversation in the game. \"For a while.\"")
                        .GoTo("r3_b3")
                    .Choice("r3_b2_b", "That must have been an easy decision.")
                        .Friendship(18)
                        .Log("\"Easiest one I ever made.\" He means it completely.")
                        .GoTo("r3_b3")
                    .Choice("r3_b2_c", "I'm sorry.")
                        .Friendship(15)
                        .Log("\"Don't be. I'd do it again.\"")
                        .GoTo("r3_b3")
                .Beat("r3_b3", "Anyway. That's why I sold.")
                    .Choice("r3_b3_a", "Is she—")
                        .Friendship(20)
                        .UnlockArc("reg_arc4")
                        .Log("He shakes his head once. Small. Definitive. You don't finish the sentence.")
                    .Choice("r3_b3_b", "*say nothing*")
                        .Friendship(20)
                        .UnlockArc("reg_arc4")
                        .Log("He finishes his drink. Orders two. Pushes one to you.")
                    .Choice("r3_b3_c", "Thank you for telling me.")
                        .Friendship(20)
                        .UnlockArc("reg_arc4")
                        .Log("\"Thank you for asking.\"")
                .Build(),

            ArcBuilder.Create(PatronId.Regular, "reg_arc4", "She liked this place", 4, FriendshipTier.Friend)
                .RequiresArc("reg_arc3")
                .Beat("r4_b1", "She used to sit right there. Third stool from the end. Said the lighting was better.")
                    .Choice("r4_b1_a", "Was it?")
                        .Friendship(15)
                        .Log("\"No. She just liked the view of the door. Liked to see who was coming in.\"")
                        .GoTo("r4_b2")
                    .Choice("r4_b1_b", "Did she like the bar?")
                        .Friendship(18)
                        .Log("\"Loved it. More than I did, honestly. She was the one who said keep it.\"")
                        .GoTo("r4_b2")
                    .Choice("r4_b1_c", "*look at the stool*")
                        .Friendship(12)
                        .Log("He nods like you've said something.")
                        .GoTo("r4_b2")
                .Beat("r4_b2", "Tuesday nights. We'd close this place down every Tuesday. Nothing happening on a Tuesday.")
                    .Choice("r4_b2_a", "Nothing wrong with Tuesdays.")
                        .Friendship(15)
                        .Log("\"That's what she said.\" He almost smiles.")
                        .GoTo("r4_b3")
                    .Choice("r4_b2_b", "Why Tuesdays?")
                        .Friendship(15)
                        .Log("\"No reason. That was the point.\"")
                        .GoTo("r4_b3")
                    .Choice("r4_b2_c", "You still come on Tuesdays?")
                        .Friendship(20)
                        .Log("He looks at his glass. \"I come every night.\"")
                        .GoTo("r4_b3")
                .Beat("r4_b3", "I don't know why I'm telling you all this.")
                    .Choice("r4_b3_a", "I don't mind.")
                        .Friendship(15)
                        .Log("\"No. I can tell.\"")
                    .Choice("r4_b3_b", "Maybe you just needed to.")
                        .Friendship(15)
                        .Log("\"Maybe.\"")
                    .Choice("r4_b3_c", "*say nothing*")
                        .Friendship(15)
                        .Log("He nods. \"Right.\"")
                .Build(),

            ArcBuilder.Create(PatronId.Regular, "reg_arc5", "Order one for her", 5, FriendshipTier.Friend)
                .RequiresArc("reg_arc4")
                .RequiresTime(660) // after 11pm
                .Beat("r5_b1", "It's her birthday today. Would have been.")
                    .Choice("r5_b1_a", "Happy birthday to her.")
                        .Friendship(25)
                        .Boredom(-10)
                        .Log("He looks at you. Nobody's ever said that.")
                        .GoTo("r5_b2")
                    .Choice("r5_b1_b", "I didn't know.")
                        .Friendship(15)
                        .Log("\"Why would you.\" Not unkindly.")
                        .GoTo("r5_b2")
                    .Choice("r5_b1_c", "Can I buy you a drink?")
                        .Friendship(20)
                        .Log("\"Buy her one. I'm fine.\"")
                        .GoTo("r5_b2")
                .Beat("r5_b2", "The bartender doesn't ask questions. Sets down two glasses.")
                    .Choice("r5_b2_a", "*raise yours*")
                        .Friendship(25)
                        .Style(15)
                        .Log("He raises his. No words. Just that.")
                    .Choice("r5_b2_b", "What did she drink?")
                        .Friendship(20)
                        .Log("\"Whatever was good. She wasn't fussy.\" He tells you. It's something simple.")
                    .Choice("r5_b2_c", "*sit with him*")
                        .Friendship(20)
                        .Log("He eventually talks about a vacation. Something small and good.")
                .Build(),

            ArcBuilder.Create(PatronId.Regular, "reg_arc6", "The Photo", 6, FriendshipTier.Friend)
                .RequiresArc("reg_arc5")
                .RequiresNight(5) // late in the week
                .Beat("r6_b1",
                    "He shows you a photo on his phone. She's laughing at something off-camera. The bar is in the background. Third stool from the end.")
                    .Choice("r6_b1_a", "She looks kind.")
                        .Friendship(50)
                        .Style(25)
                        .Log("\"She was.\" He puts the phone away. Buys you a drink. Doesn't say anything else all night. That's okay.")
                    .Choice("r6_b1_b", "*say nothing*")
                        .Friendship(50)
                        .Style(25)
                        .Log("He nods. Buys the drink. Some conversations don't need words.")
                .Build(),

            // ── Negative arcs ───────────────────────────────────────────────
            ArcBuilder.Create(PatronId.Regular, "reg_neg_cool", "Evening", 10, FriendshipTier.Cool, FriendshipTier.Cool)
                .Negative().Repeatable()
                .Beat("rn1_b1", "Evening.")
                    .Choice("rn1_any", "*any response*")
                        .Log("\"Mm.\" He goes back to his drink.")
                        .End()
                .Build(),

            ArcBuilder.Create(PatronId.Regular, "reg_neg_hostile", "Not tonight", 11, FriendshipTier.Hostile, FriendshipTier.Hostile)
                .Negative().Repeatable()
                .Beat("rnh_b1", "Not tonight.")
                    .Choice("rnh_b1_a", "What?")
                        .Friendship(-15)
                        .Log("\"I said not tonight.\" He moves his drink slightly away.")
                        .End()
                    .Choice("rnh_b1_b", "*push it*")
                        .Friendship(-25)
                        .Log("He calls the bartender over quietly. You're moved along.")
                        .End()
                    .Choice("rnh_b1_c", "*back off*")
                        .Log("Fair enough.")
                        .End()
                .Build(),

            ArcBuilder.Create(PatronId.Regular, "reg_neg_antagonist", "Know what you're doing", 12, FriendshipTier.Antagonist, FriendshipTier.Antagonist)
                .Negative().Repeatable()
                .Beat("rna_b1",
                    "I've been sitting in this bar for years. I know when someone wants to be left alone and when someone doesn't respect it. You're the second kind tonight.")
                    .Choice("rna_b1_a", "Fair enough.")
                        .Friendship(5)
                        .Log("He stays at -70. He'll talk again next night.")
                        .End()
                    .Choice("rna_b1_b", "I was just—")
                        .Friendship(-15)
                        .Log("\"I know what you were doing.\"")
                        .TriggerEvent("bartender_move_player")
                        .End()
                    .Choice("rna_b1_c", "*push further*")
                        .Friendship(-20)
                        .TriggerEvent("bartender_move_player")
                        .Log("He calls the bartender. You're moved away from the booths for the night.")
                        .End()
                .Build(),

            ArcBuilder.Create(PatronId.Regular, "reg_recovery", "Sorry about last time", 13, FriendshipTier.Cool, FriendshipTier.Cool)
                .Recovery()
                .RequiresNight(1) // must be at least night 2
                .Beat("rr_b1", "*He looks at you when you approach.*")
                    .Choice("rr_b1_a", "Sorry about last time.")
                        .Friendship(20)
                        .Log("He accepts it. Not with warmth, but he accepts it.")
                    .Choice("rr_b1_b", "*say nothing, just sit nearby*")
                        .Friendship(5)
                        .Log("He allows it.")
                .Build()
        );
    }
}
